appcad/urls.py
from django.urls import path
from . import views

app_name= 'usuarios'

urlpatterns = [
    path('cadastrara/', views.cad_view, name='criar'),
    path('lista/', views.mostrar_view, name='lista'),
    path('atualizar/<int:pk>/', views.atualizar_view , name='atualizar'),
    path('deletar/<int:pk>/', views.deletar_view, name='deletar')
]

projeto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cad/', include('appcad.urls'), name='cad')
]

appcad/models.py
from django.db import models

class Usuario(models.Model):
    nome = models.CharField(max_length=(30))
    idade = models.IntegerField()
    

appcad/forms.py
from django import forms
from .models import Usuario

class FormCad(forms.ModelForm):
    class Meta:
        model = Usuario
        
        fields = ['nome', 'idade']
        
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'idade': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome': 'NOME',
            'idade': 'IDADE',
        }

appcad/views.py
from django.shortcuts import render, redirect
from .forms import FormCad
from .models import Usuario

def cad_view(request):
    if request.method == 'GET':
        form = FormCad
        return render(request, 'cadastrar.html', {'form': form})
    elif request.method == 'POST':
            form = FormCad(request.POST)
            form.save()
            return redirect('usuarios:criar')
        
def mostrar_view(request):
    usuarios = Usuario.objects.all()
    if usuarios:
        return render(request, 'list.html', {'usuarios': usuarios})
    
def atualizar_view(request, pk):
    usuario = Usuario.objects.get(pk = pk)
    if request.method == 'POST':
        form = FormCad(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return redirect('usuarios:lista')
    else:
        form = FormCad(instance=usuario)
    return render(request, 'atualizar.html', {'form': form, 'usuario': usuario})

def deletar_view(request, pk):
    usuario = Usuario.objects.get(pk = pk)
    if request.method == 'POST':
        usuario.delete()
        return redirect('usuarios:lista')
    else:
        return render(request, 'confirmar.html', {'usuario': usuario})
    

appcad/templates/atualizar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Atualizar</title>
</head>
<body>
    <!-- Função basica para receber um form ja preenchido do usuario -->
    <h1>Atualizar usuario:</h1>
    <form action="{% url 'usuarios:atualizar' usuario.id %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <br>
            {{ field.label_tag }}
            <br>
            {{ field }}
            <br>
        {% endfor %}
        <input type="submit" value="Atualizar">
    </form>
    <button><a href="{% url 'usuarios:lista' %}">Voltar</a></button>
</body>
</html>

appcad/templates/cadastrar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'usuarios:criar' %}" method="POST">{% csrf_token %}
        {{ form }}
        <input type="submit" value="CADASTRAR">
    </form>
    <br>
    <a href="{% url 'usuarios:lista' %}"><button>Lista</button></a>
</body>
</html>

appcad/templates/confirmar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmar</title>
</head>
<body>
    <h1>Realmente deseja deletar usuario {{ usuario.nome }}?</h1>
<form method="POST">
    {% csrf_token %}
    <button type="submit">Deletar</button>
</form>
</body>
</html>

appcad/templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista dos Usuarios</title>
</head>
<body>
    <h1>Lista dos Usuarios Cadastrados</h1>
<table>
    <tr>
        <th>Nome</th>
        <th>Idade</th>
    </tr>

    {% for usuario in usuarios %}
        <tr>
            <td>{{ usuario.nome }}</td>
            <td>{{ usuario.idade }}</td>
            <td>
                <button><a href="{% url 'usuarios:atualizar' usuario.id %}">Atualizar</a></button>
                <button><a href="{% url 'usuarios:deletar' usuario.id %}">Deletar</a></button>
            </td>

        </tr>
    {% endfor %}
    <button><a href="{% url 'usuarios:criar' %}">Voltar</a></button>
</table>
</body>
</html>